name: Publish

on:
  pull_request:
  release:
    types: [released, prereleased]
    
jobs:
  version:
    name: Determine Version
    runs-on: ubuntu-18.04
    outputs:
      semver: ${{ steps.version.outputs.semver }}
      semverMajor: ${{ steps.version.outputs.semverMajor }}
      semverMajorMinor: ${{ steps.version.outputs.semverMajorMinor }}
      semverMajorMinorPatch: ${{ steps.version.outputs.semverMajorMinorPatch }}
      semverWithBuildMetadata: ${{ steps.version.outputs.semverWithBuildMetadata }}
    steps:
      - id: version
        uses: truecommerce/ghaction-version@1.2.0
            
  publish-windows:
    needs: version
    if: needs.version.outputs.semver != 0
    name: Publish Windows Installer
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: 5.0.x

      - uses: cschleiden/replace-tokens@v1.1
        with:
          files: ${{github.workspace}}/src/CloudFtpBridge.BlazorApp/Shared/MainLayout.razor
        env:
          VERSION: ${{needs.version.outputs.semver}}
      
      - uses: cschleiden/replace-tokens@v1.1
        with:
          files: ${{github.workspace}}/installer/*.iss
        env:
          VERSION: ${{needs.version.outputs.semverWithBuildMetadata}}
      
      - run: dotnet publish ${{github.workspace}}/src/CloudFtpBridge.BlazorApp/CloudFtpBridge.BlazorApp.csproj -c Release -r win-x64
      - run: '&"C:/Program Files (x86)/Inno Setup 6/iscc.exe" /Qp ${{github.workspace}}/installer/CloudFtpBridge.iss'
  
      - uses: actions/upload-artifact@v2
        with:
          name: installer
          path: ${{github.workspace}}/installer/bin
  
